### ISSUE TITLE
Future Improvements for ConnectionManager

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#1189]
With https://github.com/waku-org/js-waku/pull/1135, the `ConnectionManager` module was introduced. 

This issue intends to track future/iterative work around the same.

TODO:

- [ ] ~~write a spec test~~ tracked here: https://github.com/waku-org/js-waku/issues/1413
   - some steps to take:
      - control event emitter part of the test 
      - emit and then test dial (watch)
      - emit 2nd bootstrap peer, and shouldnt dial
      - emit px peer, and check dial
      - check peer is not dialed more than N times (attempts)

- [x] ~~add functionality to dial all available bootstrap peers if no PX peers are dialable after N seconds~~  
   - ref: https://github.com/waku-org/js-waku/pull/1135#issuecomment-1436320587

- [ ] ~~action the findings of `peer:disconnect` investigation~~ -> tracked here https://github.com/waku-org/js-waku/issues/1412
   - [x]  look into `peer:disconnect` issues described in-line in code
      -  https://github.com/waku-org/js-waku-examples/pull/219

- [x]  ~~add regular logs for available/connected nodes~~
   - [x] reach out to platform teams and confirm if this is required

- [x] confirm if the relay `keep-alive` pings are still needed
   - [x] reproduce connections timings out without the relay keep-alive and the ipfs ping logic

**Comment by fryorcraken** [comment]
Note on `peer:disconnect`: could the keep alive manager help detect dropped connections thanks to the ipfs/ping protocol?

> add regular logs for available/connected nodes

would be good to understand the needs. Talk to current platforms. Is the need mainly to debug/dog food peer exchange?

**Comment by fryorcraken** [comment]
All good findings.

You can disable relay ping in the API.
I'd use eth-pm example, disable relay ping and check that relay still works 10 minutes in.
If it does, then removing relay ping seems reasonable.

I agree with using ping to detect disconnection. Maybe we could emit an event upon ping failure to start going in this direction. And also an event upon ping reconnection.

This can then be the basis to have automated behaviour such as checking filter subscriptions or attempting store query after reconnection

**Comment by fryorcraken** [comment]
Thanks for the investigation. This is annoying because we basically spam the network with relay ping messages when they don't need to be relayed. 

Next step I suggest: open an issue to investigate why we need relay pings and understand if there's any other way to do it.
Surely, if after 10min a connection or stream close, the software should try to re-open it.

after 10min, does message sending AND receiving start failing or does only receiving fails?
