### ISSUE TITLE
switch to nwaku docker images instead of locally building 

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#1192]
This is a **change request**

## Problem

When testing nwaku interop/running tests locally, the nwaku repo needs to be cloned (the first time) & built (along with building the Nim compiler) which takes a lot of time.

## Proposed Solutions

I believe there are docker images that are released and tagged that js-waku can leverage when nwaku is required (cc @alrevuelta)

## Notes
- it would also be very easy to switch between nwaku versions without switching tags/branches and re-building 
- ⛔️**concern**: this could inhibit us from watching some nwaku logs that we rely on within the js-waku context cc @fryorcraken

**Comment by alrevuelta** [comment]
Indeed.

As an example.
```
docker run -p 8545:8545 -p 60000:60000 -p 8000:8000 statusteam/nim-waku:v0.15.0 --relay=true --discv5-discovery=true --log-level=INFO --rpc-address=0.0.0.0 --rpc-admin=true --dns-discovery-url=enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.nodes.status.im --dns-discovery=true --peer-exchange=true --log-level=DEBUG --websocket-support=True --nodekey=4a261f0c9e2ca7a19f4274bc70fa5a1685ec3857ff8001bb4a605538b7c5c25d
```

Some comments:
* Dont forget the `-p` flags to open the ports.
* `nodekey` is useful to get a deterministic peerId.
* Releases are tagged as `statusteam/nim-waku:v0.15.0`
* And specific commits can be fetched as `statusteam/nim-waku:982cd282` (8 firsts digits of the commit, only ones present in master)

Quite convenient as it doesnt require to build every commit.

Regarding the logs, no idea on how you use them, but docker logs can ofc be accessed.

**Comment by fryorcraken** [comment]
docker has an API that can give access to log from NodeJS (clean).
you can also start docker in the foreground to access log on stdout/stderr (dirty)
