### ISSUE TITLE
(re)investigate gauging peer disconnections with js-waku

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#1412]
## Problem

There have been attempts in gauging peer disconnections properly through `peer:disconnect` event listeners and the IPFS ping protocol.
Some of the efforts are tracked here: https://github.com/waku-org/js-waku/issues/1189

## Proposed Solutions

Understand how different events are emitted in context to disconnections.

With the release of libp2p 0.45.x, it might be worth it to attempt the investigation keeping in consideration the `connection:close` and `peer:disconnect` handlers exposed: https://github.com/libp2p/js-libp2p/blob/70fe699c424c22f81e39c47631fda73abc1cae9e/doc/migrations/v0.44-v0.45.md?plain=1#L143

## Notes

- should be attempted once the js-waku upgrade to libp2p 0.45.x is merged/released: https://github.com/waku-org/js-waku/pull/1400/https://github.com/waku-org/js-waku/pull/1385

**Comment by weboko** [comment]
Shouldn't be blocked anymore?
