### ISSUE TITLE
static sharding: account for multiple pubsub topics

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#1430]
This is a **support request**

## Problem

Our js-waku implementation currently only allows one `pubsubTopic`, which is used when interacting with the protocols (`lightpush`, `filter`, `store`, etc). With the introduction of sharding, it would make sense for js-waku to be able to "connect" with service nodes in different shards (multiple `pubsubTopic`). However, this requires a shift from a single `pubsubTopic` to an array (set) for js-waku.

## Proposed Solutions

1. **Multiple `pubsubTopic` Support**: Transition from a single `pubsubTopic` to an array (set) for js-waku. This will allow js-waku to connect with service nodes in different shards.

2. **Protocol Actions Update**: Protocol actions like `waku.lightpush.send(data)` currently use the default `pubsubTopic`. This method finds a suitable peer that supports the said protocol (using `getPeersForProtocol` and `selectPeerForProtocol`), and then sends a request. With the introduction of multiple `pubsubTopic`, these actions need to factor in the shard (`pubsubTopic`). We need to find a peer that is part of the shard/`pubsubTopic` as well as supports the required protocol.

3. **Peer-Shard Mapping**: We need a way to store the information about the `peerId` mapped to its shard/`pubsubTopic`. This is not trivial to do as we rely on libp2p's base types for `Peer`. This might mean creating an abstraction over that type, or storing the information in a separate variable altogether. I'm leaning towards creating an abstraction over the `Peer` type.

4. **RPC Requests Update**: The `pubsubTopic`, in the context of a particular protocol, plays a role in the creation of RPC requests. With multiple `pubsubTopic`, we need to ensure that the correct `pubsubTopic` is used when creating these requests. When `waku.lightpush.send(data)` is being called, the knowledge of the shard/`pubsubTopic` should be passed along with it. One way to do this is to create multiple `lightpush` objects on the `Waku` type/class, mapped by the `pubsubTopic`.

## Notes

Looking for feedback

Parent issue: https://github.com/waku-org/js-waku/issues/1310

**Comment by weboko** [comment]
> Multiple pubsubTopic Support: Transition from a single pubsubTopic to an array

do you mean that this array will be used to initiate `waku` node? in that case it seems that we would need some API to allow `initiate` waku node, change `pubsubTopics` on the go, and probably even set them per `send` (same as with `contentTopic` now)

but as of right now `waku` node does not care about `pubsubTopic` and it is getting set on `send` [here](https://github.com/waku-org/js-waku/blob/376bcf2a0a25bff27bc7eb04d2414ccfa9166fb5/packages/core/src/lib/light_push/index.ts#L46)
I think it should be improved and maybe moved to `IEncoder` similarly to `IDecoder` 

> Protocol Actions Update
> these actions need to factor in the shard (pubsubTopic)

in case `pubsubTopics` are set on init it seems possible to change the selection of peers, it gets trickier if we allow changing `pubsubTopics` on the go

> Peer-Shard Mapping

it would be cool to change the underlining `peerStore` but I do not see a way of doing so [here](https://github.com/libp2p/js-libp2p/blob/791f56f06bd1489d6ed29eed0517a03d6b7544fd/packages/libp2p/src/libp2p.ts#L89), we can try experimenting with newly added `services` to make end solution concise

> RPC Requests Update
> the knowledge of the shard/pubsubTopic should be passed along with it

in case we decide to initiate `waku` node with some `pubsubTopics` or not we'll still need to set `pubsubTopic` on each `send`  so I guess we can continue using the optional parameter or define it on `IEncoder` like it is done on `IDecoder`

Another category we need to mention is testing. I think we shouldn't overcomplicate our tests and cover base cases + with maybe some advanced cases as well but in a separate, optional for merging, test suit. The overhead with the number of awaits will lead to long execution and not a reliable outcome. 

Having said that to me it seems the initial implementation should have the following parts:
- 2 which is to find peers and figure out their `pubsubTopics`;
- 3 which is figure out peers to which route messages for particular `pubsubTopics`;

Properties 1 and 4 are kinda supported right now.

Maybe I missed it somewhere but:
- what behavior should be in case `waku` node does not know a peer with `pubsubpTopic = X` but wants to send a message to it?
- is it possible to send one message to multiple shards?

@SionoiS can you educate me on 2 questions above?

**Comment by SionoiS** [comment]
> * what behavior should be in case `waku` node does not know a peer with `pubsubpTopic = X` but wants to send a message to it?
> * is it possible to send one message to multiple shards?
> 
> @SionoiS can you educate me on 2 questions above?

ENRs encode the sharding information for nodes and discovery will ignore peers on other shards, resulting in a selection of peers on the same shards.

As for sending messages, yes for static sharding, no for autosharding.
If a node is setup for static shards them it's possible but unlikely that a message would be sent on multiple shards. For autosharding, a content topic will always map to a specific shard.

**Comment by fryorcraken** [comment]
> If a node is setup for static shards them it's possible but unlikely that a message would be sent on multiple shards. For autosharding, a content topic will always map to a specific shard.

I think it's fair to assume that a message is set to a single shard and if the developer wants it to send to 2 shards, then it should two calls.

> in case we decide to initiate waku node with some pubsubTopics or not we'll still need to set pubsubTopic on each send so I guess we can continue using the optional parameter or define it on IEncoder like it is done on IDecoder

There is definitely both needed which makes things complicated:
- Each message being send or each subscription being done should specify the shard to use
- The node needs to be aware of the shard "we" are currently interesting in to do proper peer management.,.

I think in the context of js-waku, we can assume that the shards we are interesting in will not change mid-run because Status Web handles one Status Community at a time. @felicio @prichodko can you confirm?

So in this case, we can pass static shard at initialization. I would also recommend to fail if one pass an encoder or decoder for a shard that is not part of the initialisation.

static sharding is a temporary solution so no need to overengineer the solution.

Then we can review with auto-sharding how we handle peers and shards.

**Comment by weboko** [comment]
> ENRs encode the sharding information for nodes and discovery will ignore peers on other shards, resulting in a selection of peers on the same shards.

@SionoiS so we need to discover nodes for shards we are interested in. That means that sending a message to a shard `X` without having such a node discovered - is impossible. Is it right?

> static sharding is a temporary solution so no need to overengineer the solution.

so something basic shall be enough?

```ts
const node = createRelayNode({ pubsubTopics: ["A", "B", "C"] });
const encoder = createEncoder({ contentTopic: "X", pubsubTopic: "A" });

node.send(encoder, message); // fails if `pubsubTopic=A` was not used for initialization 
```

**Comment by SionoiS** [comment]
> @SionoiS so we need to discover nodes for shards we are interested in. That means that sending a message to a shard `X` without having such a node discovered - is impossible. Is it right?

True.

**Comment by fryorcraken** [comment]
> ```ts
> const node = createRelayNode({ pubsubTopics: ["A", "B", "C"] });
> const encoder = createEncoder({ contentTopic: "X", pubsubTopic: "A" });
> 
> node.send(encoder, message); // fails if `pubsubTopic=A` was not used for initialization 
> ```

I would focus on providing the static shard API instead of pubsub topic one:

```ts

const M=0
const N=1

const node = createRelayNode({ cluster: M, shards: [N, O] });
const encoder = createEncoder({ contentTopic: "/myapp/0/name/proto", shard: N, cluster: M });

node.send(encoder, message); // fails if `pubsubTopic=A` was not used for initialization 
```

**Comment by fryorcraken** [comment]
> > I would focus on providing the static shard API instead of pubsub topic one:
> > ```ts
> > const M=0
> > const N=1
> > 
> > const node = createRelayNode({ cluster: M, shards: [N, O] });
> > const encoder = createEncoder({ contentTopic: "/myapp/0/name/proto", shard: N, cluster: M });
> > 
> > node.send(encoder, message); // fails if `pubsubTopic=A` was not used for initialization 
> > ```
> 
> i agree; however, with this, will we still allow users to be able to pass `pubsubTopic` as `string` for people who don't want to use the sharded Waku Network?

Named shard: https://rfc.vac.dev/spec/51/#named-sharding is defined in our RFC so I guess we should keep support for it. @jm-clius @alrevuelta, any thoughts on this?

**Comment by SionoiS** [comment]
Named, Static and Auto sharding should all be valid options IMO.

**Comment by jm-clius** [comment]
Indeed. I would keep support for named sharding. Think of the static shard format/autosharding as a middleware convenience API that builds on top of the named shard APIs - it simply allows applications to interact using cluster IDs/shard numbers and construct the pubsub topic string on behalf of the application. Once the pubsub topic string has been created for a static shard, it behaves like a named shard.

**Comment by fryorcraken** [comment]
> Sounds good.
> 
> Conclusion is to have the API take in a `string` instead of the an object like `{cluster: M, shards: [N,0]}` (to allow for named pubsub topic support as well) and js-waku will interpret it internally
> 
> @fryorcraken let me know if you think otherwise

Well I think it should take either so that a developer taht uses static sharding doe snot ahve to think how to construct the pubsub string...
