### ISSUE TITLE
peer-exchange browser feedback

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#1454]
This PR is meant to track the feedback and dial errors encountered via peer exchange on browser using the web-chat example, and is part of the milestone https://github.com/waku-org/js-waku/issues/1429 and https://github.com/waku-org/js-waku/issues/1326

Related:
- https://github.com/waku-org/js-waku/issues/1309
- https://discord.com/channels/1110799176264056863/1111541029309534249/1136633301386412062

**Comment by SionoiS** [comment]
After some time I got.

Peers Discovered: 126
Bootstrap: 2 Peer Exchange: 124
Peers Connected: 18
Bootstrap: 2 Peer Exchange: 16

and mostly WSS errors.

**Comment by chaitanyaprem** [comment]
Left for a long time and noticed below. 

<img width="310" alt="Screenshot 2023-08-03 at 9 40 59 PM" src="https://github.com/waku-org/js-waku/assets/20137744/335cfcb6-15f5-4fbb-af08-62fe7da4cb9d">

Only logs were errors like below

`The connection to wss://node-02.gc-us-central1-a.status.prod.statusim.net/p2p/16Uiu2HAmDQugwDHM3YeUp86iGjrUvbdw3JPRgikC7YoGBsT2ymMg was interrupted while the page was loading.`

**Comment by fryorcraken** [comment]
@mfw78 what's the setup on dappnode? I see some `ws` error, can we ensure that nwaku is configured using wss by default?

**Comment by fryorcraken** [comment]
I am getting

```
 Firefox can’t establish a connection to the server at wss://node-01.do-ams3.wakuv2.prod.statusim.net:8000/p2p/16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e.
 Firefox can’t establish a connection to the server at wss://node-01.gc-us-central1-a.wakuv2.prod.statusim.net:8000/p2p/16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA.
```

Despite node connections being quite low: https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&refresh=30s&var-host=node-.%2A&var-fleet=wakuv2.test&var-fleet=wakuv2.prod&var-dc=All&from=now-2d&to=now&viewPanel=2&editPanel=2

Do we not log our own PeerId? Needed to investigate on nwaku side.

**Comment by fryorcraken** [comment]
Same in Brave:
```
main.10c2788a.js:1 waku:peer-discovery-dns Use following EIP-1459 ENR Tree URLs:  +0ms ['enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.waku.nodes.status.im']
15:12:55.436 main.10c2788a.js:1 waku:peer-discovery-dns Starting peer discovery via dns +84ms
15:12:55.440 main.10c2788a.js:1 waku:peer-exchange-discovery Starting peer exchange node discovery, discovering peers +0ms
15:12:55.961 main.10c2788a.js:1 waku:discovery:fetch_nodes got new peer candidate from DNS address=40ac1a3894f347e04f7fa105c6e2b1a31af5cf68cdd10df9bb6e5e3e576b855a@188.166.135.145 +0ms
15:12:56.122 main.10c2788a.js:1 waku:discovery:fetch_nodes got new peer candidate from DNS address=5ca27c4d8f796b85475e03f326fd045241668f4f25bc3de0a9bc8a1ae29d7894@8.210.222.231 +161ms
15:12:56.133 main.10c2788a.js:1 waku:waku Waku node created +0ms 12D3KooWRSPam6T7v1WV7pw4BTdzbfN9mcxLekZspnHp4XZeFrnS relay: false, store: true, light push: true, filter: true
15:12:56.134 main.10c2788a.js:1 waku:connection-manager Connection Manager is now running +0ms
15:12:56.212 main.10c2788a.js:1 waku:connection-manager Dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e on attempt 1 +78ms
15:12:56.214 main.10c2788a.js:1 waku:connection-manager Dialing peer 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD on attempt 1 +1ms
15:13:26.156 main.10c2788a.js:1 WebSocket connection to 'wss://node-01.ac-cn-hongkong-c.wakuv2.prod.statusim.net:8000/p2p/16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD' failed: WebSocket is closed before the connection is established.
(anonymous) @ main.10c2788a.js:1
close @ main.10c2788a.js:1
a @ main.10c2788a.js:1
r @ main.10c2788a.js:1
r @ main.10c2788a.js:1
15:13:26.160 main.10c2788a.js:1 waku:connection-manager Error dialing peer 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD - The operation was aborted +30s
15:13:26.161 main.10c2788a.js:1 waku:connection-manager Dialing peer 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD on attempt 2 +1ms
15:13:26.171 main.10c2788a.js:1 WebSocket connection to 'wss://node-01.do-ams3.wakuv2.prod.statusim.net:8000/p2p/16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e' failed: WebSocket is closed before the connection is established.
(anonymous) @ main.10c2788a.js:1
close @ main.10c2788a.js:1
a @ main.10c2788a.js:1
r @ main.10c2788a.js:1
r @ main.10c2788a.js:1
15:13:26.172 main.10c2788a.js:1 waku:connection-manager Error dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e - The operation was aborted +11ms
15:13:26.172 main.10c2788a.js:1 waku:connection-manager Dialing peer 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e on attempt 2 +0ms
```

**Comment by mfw78** [comment]
> @mfw78 what's the setup on dappnode? I see some `ws` error, can we ensure that nwaku is configured using wss by default?

`nwaku` actually runs as `ws`, and *not* `wss` as TLS is handled by a proxy within dappnode. This proxy is responsible for auto-configuring over the SSL certificates etc.

**Comment by fryorcraken** [comment]
> > @mfw78 what's the setup on dappnode? I see some `ws` error, can we ensure that nwaku is configured using wss by default?
> 
> `nwaku` actually runs as `ws`, and _not_ `wss` as TLS is handled by a proxy within dappnode. This proxy is responsible for auto-configuring over the SSL certificates etc.

Fair but is nwaku in dappnode configured so that it advertised itself using the wss proxy multiaddr and NOT the ws one? looks like it ain't happening sometimes.

**Comment by fryorcraken** [comment]
Regarding dappnode, we can open an orphan issue for now and track with @mfw78 to understand what can be done.

What is the second issue about? I'd suggest we investigate a bit more before considering peer exchange as done.

**Comment by fryorcraken** [comment]
Some more feedback:
- `Peers Connected` on right and left do not always match, especially on mobile
- Are `Peers Discovered` only wss peers?

**Comment by fryorcraken** [comment]
>     * `Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Payload identity key does not match expected remote peer`

Interestingly enough this is a fleet peer:

```
common.js:113 libp2p:connection-manager:dial-queue:error error during dial of /dns4/node-01.gc-us-central1-a.wakuv2.prod.statusim.net/tcp/8000/wss/p2p/16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA/p2p/16Uiu2HAmEhN1JUTSVau1xf71a8z7web8b7kTMv2xZD6JwJ8UT19q +948ms CodeError: Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Payload identity key 16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA does not match expected remote peer 16Uiu2HAmEhN1JUTSVau1xf71a8z7web8b7kTMv2xZD6JwJ8UT19q
```

so we should investigate as part of peer exchange milestone.

**Comment by fryorcraken** [comment]
Actually, if js-waku can connect to a Status desktop node via a fleet node thanks to rendezvous to consume filter and lightpush that would be beneficial.

While the js-waku node would still hog a connection on the fleet (rendezvous) node and take bandwidth (but only to send messages and receive messages on specific content topic), the usage of memory resources to hold the subscription would be delegated to the Status Desktop node. I assume it would not consume one more connection on the status desktop node either as the connection to the rendezvous node is re-used.

@richard-ramos @waku-org/research is my analysis corect?

**Comment by fryorcraken** [comment]
Note that peer exchange can be tracked in a browser scalability milestone yet to be created.

**Comment by chaitanyaprem** [comment]
> That is a very nice idea @fryorcraken . This way the load of light clients can be distributed to the nodes in the network rather than just the fleets making it more decentralized.

Wrt connection, same libp2p connection will be reused for multiple protocols as it is the same peer.

**Comment by jm-clius** [comment]
> Actually, if js-waku can connect to a Status desktop node via a fleet node thanks to rendezvous to consume filter and lightpush that would be beneficial.

Agree here that connecting to distributed nodes for filter and lightpush is beneficial. Currently Status Desktop nodes do the same. What I'm confused about is why this necessarily has to be discovered via rendezvous? Status Desktop nodes are discoverable in most cases via discv5 and peer exchange. For now, we suggest peer exchange as better discovery mechanism than rendezvous, as it's less prone to neighbourhood-effects. Rendezvous is useful to discover nodes behind a NAT and coordinating a hole punch.

**Comment by richard-ramos** [comment]
> I think. Is that even the correct multiaddr format for rendezvous? cc @richard-ramos

This is not a correct multiaddress format as it is missing the `p2p-circuit` component. Where is this address from?

**Comment by richard-ramos** [comment]
> I assume it would not consume one more connection on the status desktop node either as the connection to the rendezvous node is re-used.

yeah, libp2p does stream multiplexing, so a single connection can be reused for multiple protocols

**Comment by fryorcraken** [comment]
@jm-clius my bad, wherever I said "rendezvous" I actually meant "p2p-circuit" Thanks @richard-ramos for jumping in.

> This is not a correct multiaddress format as it is missing the p2p-circuit component. Where is this address from?

Maybe older Status Desktop versions? Would be good to see if we successfully find and connect to p2p-circuit addresses via peer exchange cc @danisharora099

**Comment by richard-ramos** [comment]
@danisharora099 let me know if i can help. FWIW the go-waku test/prod fleets should have circuit relay enabled so maybe they can be used to force an scenario win which p2p circuit addresses appear in peer exchange.
