### ISSUE TITLE
bug: flaky peer-exchange compliance test

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#1477]
This is a bug report

## Problem

The peer-exchange compliance test within js-waku has been inconsistent and flaky on its runs:
it was seen to be flakily passing/failing based on local/CI envs without any reproducible/deterministic way. 
Recently during some deps upgrade, this flaky test started to consistently fail in the CI while inconsistently passing in the local env.
Certain attempts like https://github.com/waku-org/js-waku/pull/1468 were made to resolve this.

## Proposed Solutions

To be figured out

## Notes

> Failing peer-exchange compliance test might be related to https://github.com/libp2p/js-libp2p/issues/1846

> investigation led to a conclusion that `peer:update`/`peer:identify` might not be get triggered within the CI
(https://github.com/waku-org/js-waku/pull/1472#issuecomment-1675944556)

- Might be related to https://github.com/libp2p/js-libp2p/issues/1846 (https://github.com/libp2p/js-libp2p/issues/1846#issuecomment-1675943647)

**Comment by weboko** [comment]
Next steps: 
- do profiling and try to get it happen locally;
- check logs step by step
