### ISSUE TITLE
peer-exchange: dappnode advertises `ws` instead of `wss`

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#1526]
This is a bug report

## Problem

During investigation around peer-exchange in browser (https://github.com/waku-org/js-waku/issues/1454), it was found out that some of the nodes run in dappnode actually advertise `ws` ports instead of `wss` probably because TLS is handled by a proxy within dappnode

This issue is to track the correct advertisement within dappnode, and their reachability.

---- 

@mfw78 is this something you can help look into perhaps?

**Comment by mfw78** [comment]
From my understanding there is no method to restrict what gets advertised (but you can only add _additional_ multiaddrs), so they are advertising both `ws` and `wss`.
