### ISSUE TITLE
bug: ApplicationInfo to PubsubTopic doesn't take clusterId into consideration

### ISSUE THREAD

**Issue by fbarbu15** [logos-messaging/logos-delivery-js#1902]
This is a **bug report**

## Problem

[shardInfoToPubsubTopics](https://github.com/waku-org/js-waku/blob/master/packages/utils/src/common/sharding.ts#L68) and [ensureShardingConfigured](https://github.com/waku-org/js-waku/blob/master/packages/utils/src/common/sharding.ts#L295) doesn't take `clusterId` into consideration when resolving the `PubsubTopic` for `ApplicationInfo`

IMO this needs to work because `ApplicationInfo` also contains `clusterId` and I expect the `PubsubTopic` to match it

## Proposed Solutions

`clusterId` needs to be passed to `contentTopicToPubsubTopic` in those 2 functions

**Comment by danisharora099** [comment]
related to https://github.com/waku-org/nwaku/issues/2502
