### ISSUE TITLE
feat: map/use correct bootstrap nodes fleet according to the configured pubsub topic

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#2011]
This is a **bug report**

## Problem

By default, we are currently bootstrapping into the fleet with TWN, while by default on js-waku, we used the `DefaultPubsubTopic`

We currently bootstrap into the `SANDBOX` fleet.

## Proposed Solutions

Use the correct fleet according to the configured pubsub topic:
- wakuv2.test for `DefaultPubusbTopic`
- waku.sandbox for `TWN` (note: js-waku does not currently support TWN)

**Comment by weboko** [comment]
Moving in progress as @danisharora099 started working on it.
