### ISSUE TITLE
feat: store v3

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#2029]
This is a **feature request**

## Problem

We now have new version for the Store protocol, Store V3, with significant advantages over the, now, legacy Store V2.
The main advantage is the ability to query a Store node which only returns the stores message hashes, instead of returning the entire messages. This makes the protocol queries very lightweight, advantageous in scenarios like https://github.com/waku-org/js-waku/issues/2008

## Proposed Solutions

Implement the Store V3 protocol.

**Comment by weboko** [comment]
Blocking item wa resolved.

**Comment by weboko** [comment]
I think we can start looking into it before the release with locally run `nwaku` node, @danisharora099
