### ISSUE TITLE
chore(peer-exchange): support updates of previously discovered peer's addresses 

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-js#2051]
This is a potential **bug report**

## Problem

Based on https://github.com/waku-org/go-waku/pull/1128, it was found out that status-go runs into a problem where if a peer is discovered dynamically, perhaps using Peer Exchange, the peer is stored in the Peer Store with certain TTL. In case the peer is discovered again, in case with updated addresses, it is discarded because we assume that we already have knowledge about its information, but the addresses might be refreshed.

## Proposed Solutions

Account for the change of addresses observed, when the same peer is discovered again in Peer Exchange

**Comment by weboko** [comment]
Part of Reliability milestone.
